language: r
sudo: no
cache: packages
warnings_are_errors: yes
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
addons:
  apt:
    packages:
    - libmagick++-dev
    - libssh2-1-dev
matrix:
  include:
  - r: oldrel
  - r: release
    env: DEPLOY_PAGES=true
    r_github_packages:
    - krlmlr/pkgdown@develop
    - krlmlr/travis@develop
    r_packages:
    - covr
    - roxygen2
  - r: devel
  - os: osx
    osx_image: xcode7.2
    r: release
    latex: no
r_packages: covr
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
- scripts/deploy-pages.sh
- R -e 'covr::codecov()'; fi
- R -e "travis::deploy(tasks = c('travis::task_install_ssh_keys()'))"
r_github_packages: ropenscilabs/travis

